version: '2'
services:
  nginx:
    container_name: nginx
    restart: always
    privileged: true
    image: kbqallan/nginx:latest
    network_mode: host
    environment:
    - TERM=linux
    - DEFAULT_CONF=disable
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /data/wwwroot:/data/wwwroot:rw
    - /data/wwwlogs:/data/wwwlogs:rw
    - /usr/local/nginx/conf:/usr/local/nginx/conf:rw
