version: '2'

services:
  nginx:
    build:
      context: https://github.com/xiaoyawl/docker-nginx.git
    restart: always
    image: nginx:1.10.1
    container_name: nginx
    ports:
    - "80:80"
    volumes:
    - /data/wwwroot:/data/wwwroot
    - /etc/localtime:/etc/localtime
